### ISSUE TITLE
Grammar rules with a direct `include` not supported

### ISSUE THREAD

**Issue by SimonCockx** [NeekSandhu/monaco-textmate#13]
The following works in VS Code, but does not work in Monaco.
```
repository:
  ruleA:
    include: '#ruleB'
  ruleB:
    match: '[a-zA-Z]+'
```
Note that `ruleA` directly includes `ruleB`.

Current workaround:
```
repository:
  ruleA:
    patterns:
    - include: '#ruleB'
  ruleB:
    match: '[a-zA-Z]+'
```
